import localFont from 'next/font/local';

import { AuthProvider } from '@/components';

import 'react-day-picker/style.css';
import './globals.css';

const helix = localFont({ src: '../assets/fonts/Hellix-Regular.woff' });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={helix.className}>
				<AuthProvider>
					<div>{children}</div>
				</AuthProvider>
			</body>
		</html>
	);
}
