'use client';

import { useEffect } from 'react';
import localFont from 'next/font/local';

import { AuthProvider } from '@/components';

import 'react-day-picker/style.css';
import './globals.css';

const helix = localFont({ src: '../assets/fonts/Hellix-Regular.woff' });

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
	// useEffect(() => {
	// 	function handleWheel(e) {
	// 		e.preventDefault();
	// 	}
	// 	window.addEventListener('wheel', (e) => handleWheel(e), {
	// 		passive: false,
	// 	});

	// 	return () =>
	// 		window.removeEventListener('wheel', (e) => handleWheel(e), {
	// 			passive: false,
	// 		});
	// }, []);

	useEffect(() => {
		// if (document.querySelector('.overflow-y-auto')) {
		// 	document
		// 		.querySelector('.overflow-y-auto')
		// 		.addEventListener('click', (event) => {
		// 			console.log('OK');
		// 		});
		// }
		// const allWithClass = Array.from(
		// 	document.getElementsByClassName('overflow-y-auto')
		// );
		// function handleWheel(e) {
		// 	// e.preventDefault();
		// 	console.log('Hi');
		// }
		// allWithClass.forEach((element) => {
		// 	element.addEventListener('wheel', (event) => {
		// 		console.log('OK');
		// 	});
		// });
		// return () =>
		// 	allWithClass.forEach((element) => {
		// 		element.removeEventListener('wheel', (e) => handleWheel(e), {
		// 			passive: false,
		// 		});
		// 	});
	}, []);

	return (
		<html lang="en">
			<body className={helix.className}>
				<AuthProvider>
					<div className="h-full">{children}</div>
				</AuthProvider>
			</body>
		</html>
	);
}
